<?php
/**
 * @var $block \Dolphin\OrderSection\Block\Adminhtml\Order\View\Tab\CustomTab
 */
?>
<form id="ord_form" action="<?php echo $this->getUrl('customsales/order/senddetails'); ?>" method="post">
<input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
<div class="fieldset-wrapper order-information">
    <div class="fieldset-wrapper-title">
       <span class="title"><?php /* @escapeNotVerified */
           echo __('Custom Information for new tab') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
        <?php echo $block->getChildHtml(); ?>
        <tr>
            <th><?php /* @escapeNotVerified */
                echo __('Order ID :') ?></th>
		<td>		
			<select name="order_id" id="order_id">
				<option selected="selected" value="<?= $block->getOrderIncrementId() ?>">
					<?php /* @escapeNotVerified */
				        echo __('Order ID :') ?>
					<?= $block->getOrderIncrementId(); ?>
				</option>
			</select>
		</td>
        </tr>
	<tr>
		<th></th>
	        <td>
	        	<button name="loaddata" id="load_order">Load</button>
		</td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */
                echo __('Order info :') ?></th>
            <td><textarea name="order_info" id="order_info"></textarea></td>
        </tr>
	<tr>
		<th></th>
	        <td>
	        	<button type="" form="ord_form" name="senddata" id="send_order">Send</button>
		</td>
        </tr>
        </tbody>
    </table>
</div>
</form>
<script>
require(['jquery', 'jquery/ui'], function($){
        var detailajaxRequest;
	var dataForm = $('#ord_form');
        jQuery("#load_order").on('click',function(e){
        e.preventDefault();
        detailajaxRequest = jQuery.ajax({
            url: "<?php echo $this->getUrl('customsales/order/details', ['_nosid' => true]); ?>",
            type: 'GET',
            data: {order_id : $('#order_id').val(),form_key: window.FORM_KEY}, //exemple
            dataType: 'json',
            beforeSend: function () {
                jQuery('#loader').show();
            }
        });
            //Show successfully for submit message
        detailajaxRequest.done(function (response, textStatus, jqXHR) {
            jQuery("#order_info").text(JSON.stringify(response, null, "\t"));
            jQuery('#loader').hide();
        });

            //On failure of request this function will be called
        detailajaxRequest.fail(function () {
            //show error
		jQuery("#order_info").text("hi");
            jQuery('#loader').hide();
        });
        
    });
	    	
});
</script>
